camunda.bpm.admin-user:
  id: demo
  password: demo

spring.mvc.pathmatch.matching-strategy: ant_path_matcher

server:
  port : 8080

spring.jpa:
  show-sql: true
  properties.hibernate.format_sql: true

camunda.bpm:
  database:
    schema-update: create-drop
    type: postgres
spring.datasource:
  url: "jdbc:postgresql://localhost:5432/postgres?currentSchema=camunda"
  username: postgres
  password: postgres
  driverClassName: org.postgresql.Driver
  show-sql: true
  createSchemaIfNotExists: true

